apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab7-deployment
  labels:
    app: lab7-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab7-app
  template:
    metadata:
      labels:
        app: lab7-app
    spec:
      containers:
        - name: lab7-container
          image: krishnasinghcode/lab7-app:24
          ports:
            - containerPort: 3000