apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab8-deployment-blue
  labels:
    app: lab8-app
    version: blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab8-app
      version: blue
  template:
    metadata:
      labels:
        app: lab8-app
        version: blue
    spec:
      containers:
      - name: lab8-app
        image: krishnasinghcode/lab7-app:22   # or latest tag Jenkins set
        ports:
        - containerPort: 3000
        env:
        - name: APP_VERSION
          value: "blue"