FROM jenkins/jenkins:lts

USER root

# Install kubectl (simple curl-based install)
RUN apt-get update && apt-get install -y ca-certificates curl && \
    curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && \
    chmod +x kubectl && mv kubectl /usr/local/bin/kubectl && \
    rm -rf /var/lib/apt/lists/*

# Back to jenkins user by default
USER jenkins