apiVersion: v1
kind: Service
metadata:
  name: lab8-service
spec:
  type: NodePort
  selector:
    app: lab8-app
    version: blue       # initially route to blue
  ports:
  - port: 80
    targetPort: 3000    # same as containerPort above
    nodePort: 30081     # a free NodePort