apiVersion: v1
kind: Service
metadata:
  name: lab7-service
spec:
  selector:
    app: lab7-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080